# Generated by Django 4.2.4 on 2023-08-26 15:23

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelLitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('fuel_litres', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LitresBeforeNextTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('litres', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
            options={
                'verbose_name_plural': 'Litres before next top up',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name_plural': 'Fuel price',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=5)),
                ('litres_per_day', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_sold_litres', models.DecimalField(decimal_places=4, max_digits=9)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
