# Generated by Django 4.2.4 on 2023-08-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sale_total_sold_litres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuellitre',
            name='fuel_litres',
            field=models.PositiveSmallIntegerField(verbose_name='Fuel litres (Update fuel litres on every top up.)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_sold_litres',
            field=models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Current litres of sold fuel'),
        ),
    ]
